# Generated by Django 6.0.4 on 2026-05-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='photo',
            field=models.ImageField(null=True, upload_to='donate/'),
        ),
    ]
