# Generated by Django 5.2.13 on 2026-04-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='напишите название блога')),
                ('description', models.TextField(blank=True, verbose_name='напишите статью')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='загрузите изображение')),
                ('blog_file', models.FileField(upload_to='blog/', verbose_name='загрузите pdf файл')),
                ('type_blog', models.CharField(choices=[('програмирование', 'програмирование'), ('бизнес', 'бизнес'), ('медицина', 'медицина')], default='програмирование', max_length=100)),
                ('createted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
