# Generated by Django 5.2.13 on 2026-04-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='quantity',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Укажите количество страниц'),
        ),
    ]
