# Generated by Django 6.0.4 on 2026-04-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='quantity',
            field=models.PositiveIntegerField(default=20, null=True, verbose_name='укажите кол-во страниц'),
        ),
    ]
